### ISSUE TITLE
EC2 Instance IAM Role based credentials failing

### ISSUE THREAD

**Issue by clarkm5** [sous-chefs/aws#338]
### Cookbook version
7.2.2
### Chef-client version
13.7.16

### Platform Details
AWS EC2 - any instance type but easiest to reproduce with m5.large (testing in eu-west-1)

### Scenario:
Using EC2 Instance IAM Role based credentials
For example - Attempting to retrieve files from S3 using aws_s3_file during chef run called by userdata script
Any resource will fail - this is not specific to the aws_s3_file resource
This does not fail every time - it is around 40% to 50% of the time with m5.large

### Steps to Reproduce:
Create a new EC2 instance - preferably m5.large, any Linux O/S (tested with latest Amazon Linux 2)
Assign an IAM Role to the instance with appropriate permissions to GET files from an S3 bucket
Create a simple recipe to get the file using aws_s3_file and deposit anywhere on the instance
Execute the chef run in the userdata script

### Expected Result:
aws_s3_file resource should use the EC2 Instance IAM Role creds to auth to S3 so that we can get the file.

### Actual Result:
Authentication fails - with an error such as this one:
[2018-01-25T13:00:09+00:00] ERROR: aws_s3_file had an error: Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:  
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider

Looking at libraries/ec2.rb, we saw that when reverting to the local credential chain, the defaults for timeout and delay are very harsh.  For some reason this issue is more prevalent on the new M5 instance type.

The following change has provided a workaround as the default number of retries is zero - it would be good to be able to configure the default number of retries and delay using attributes.

```
@@ -77,6 +77,8 @@ module AwsCookbook
             new_resource.aws_session_token)
         else
           Chef::Log.debug('Using local credential chain')
+          creds = ::Aws::InstanceProfileCredentials.new(retries: 5, delay: 5)
+          aws_interface_opts[:credentials] = creds
         end
```

**Comment by majormoses** [comment]
Interesting I have not seen this myself, it does make sense to add some retries and make that exposed somehow.

**Comment by lewisgaines** [comment]
I am consistently seeing this issue when trying to retrieve a file from s3 on hosts running Windows Server 2019 and Chef client v14.13.11. The same cookbook runs fine on Windows Server 2012R2 hosts with the same IAM role applied to the host.
