### ISSUE TITLE
Need Sample Code for Coldfusion to download files from S3

### ISSUE THREAD

**Issue by dphoto20** [sous-chefs/aws#446]
HI I have no issues uploading but have no way to download  when a user clicks on Download button. Any sample code Jquery with Coldfusion or any Coldfusion sample code

**Comment by majormoses** [comment]
Unfortunately this is not a great place to ask for this help. This project is focused on the chef ecosystem and that's well outside of the scope of the project. I would recommend seeking help in community projects in the coldfusion space.  I did find this that might be worth looking at:
- https://helpx.adobe.com/coldfusion/using/integrate-coldfusion-amazon-s3.html
- https://brianklaas.net/assets/pdf/StartUsingAWSinYourCFApps-Klaas.pdf
- https://gist.github.com/Leigh-/26993ed79c956c9309a9dfe40f1fce29
- https://stackoverflow.com/questions/67583678/coldfusion-trying-to-upload-files-in-aws-s3
